from typing import Any, Dict, Optional

WORDING : Dict[str, Any] =\
{
	'conda_not_activated': 'Conda не активирована',
	'python_not_supported': 'Требуется Python {version} или выше',
	'curl_not_installed': 'Curl не установлен',
	'ffmpeg_not_installed': 'FFmpeg не установлен',
	'creating_temp': 'Создание временных файлов',
	'extracting_frames': 'Извлечение кадров ({resolution}, {fps} FPS)',
	'extracting_frames_succeed': 'Кадры успешно извлечены',
	'extracting_frames_failed': 'Ошибка извлечения кадров',
	'analysing': 'Анализ',
	'extracting': 'Извлечение',
	'streaming': 'Трансляция',
	'processing': 'Обработка',
	'merging': 'Слияние',
	'downloading': 'Загрузка',
	'temp_frames_not_found': 'Временные кадры не найдены',
	'copying_image': 'Копирование изображения ({resolution})',
	'copying_image_succeed': 'Изображение успешно скопировано',
	'copying_image_failed': 'Ошибка копирования изображения',
	'finalizing_image': 'Завершение обработки изображения ({resolution})',
	'finalizing_image_succeed': 'Изображение успешно обработано',
	'finalizing_image_skipped': 'Пропуск завершения обработки изображения',
	'merging_video': 'Слияние видео ({resolution}, {fps} FPS)',
	'merging_video_succeed': 'Видео успешно объединено',
	'merging_video_failed': 'Ошибка объединения видео',
	'skipping_audio': 'Пропуск аудио',
	'replacing_audio_succeed': 'Аудио успешно заменено',
	'replacing_audio_skipped': 'Пропуск замены аудио',
	'restoring_audio_succeed': 'Аудио успешно восстановлено',
	'restoring_audio_skipped': 'Пропуск восстановления аудио',
	'clearing_temp': 'Очистка временных файлов',
	'processing_stopped': 'Обработка остановлена',
	'processing_image_succeed': 'Обработка изображения завершена за {seconds} секунд',
	'processing_image_failed': 'Ошибка обработки изображения',
	'processing_video_succeed': 'Обработка видео завершена за {seconds} секунд',
	'processing_video_failed': 'Ошибка обработки видео',
	'choose_image_source': 'Выберите изображение для источника',
	'choose_audio_source': 'Выберите аудио для источника',
	'choose_video_target': 'Выберите видео для цели',
	'choose_image_or_video_target': 'Выберите изображение или видео для цели',
	'specify_image_or_video_output': 'Укажите выходное изображение или видео в папке',
	'match_target_and_output_extension': 'Сопоставьте расширение цели и выходного файла',
	'no_source_face_detected': 'Лицо источника не обнаружено',
	'processor_not_loaded': 'Процессор {processor} не может быть загружен',
	'processor_not_implemented': 'Процессор {processor} реализован неправильно',
	'ui_layout_not_loaded': 'Макет интерфейса {ui_layout} не может быть загружен',
	'ui_layout_not_implemented': 'Макет интерфейса {ui_layout} реализован неправильно',
	'stream_not_loaded': 'Поток {stream_mode} не может быть загружен',
	'stream_not_supported': 'Поток не поддерживается',
	'job_created': 'Задача {job_id} создана',
	'job_not_created': 'Ошибка создания задачи {job_id}',
	'job_submitted': 'Задача {job_id} отправлена',
	'job_not_submitted': 'Ошибка отправки задачи {job_id}',
	'job_all_submitted': 'Все задачи отправлены',
	'job_all_not_submitted': 'Ошибка отправки всех задач',
	'job_deleted': 'Задача {job_id} удалена',
	'job_not_deleted': 'Ошибка удаления задачи {job_id}',
	'job_all_deleted': 'Все задачи удалены',
	'job_all_not_deleted': 'Ошибка удаления всех задач',
	'job_step_added': 'Шаг добавлен в задачу {job_id}',
	'job_step_not_added': 'Ошибка добавления шага в задачу {job_id}',
	'job_remix_step_added': 'Шаг ремикса добавлен в задачу {job_id} (шаг {step_index})',
	'job_remix_step_not_added': 'Ошибка добавления шага ремикса в задачу {job_id} (шаг {step_index})',
	'job_step_inserted': 'Шаг вставлен в задачу {job_id} (шаг {step_index})',
	'job_step_not_inserted': 'Ошибка вставки шага в задачу {job_id} (шаг {step_index})',
	'job_step_removed': 'Шаг удален из задачи {job_id} (шаг {step_index})',
	'job_step_not_removed': 'Ошибка удаления шага из задачи {job_id} (шаг {step_index})',
	'running_job': 'Запуск задачи {job_id}',
	'running_jobs': 'Запуск задач',
	'retrying_job': 'Повторная попытка задачи {job_id}',
	'retrying_jobs': 'Повторная попытка задач',
	'processing_job_succeed': 'Задача {job_id} успешно обработана',
	'processing_jobs_succeed': 'Все задачи успешно обработаны',
	'processing_job_failed': 'Ошибка обработки задачи {job_id}',
	'processing_jobs_failed': 'Ошибка обработки задач',
	'processing_step': 'Обработка шага {step_current} из {step_total}',
	'validating_hash_succeed': 'Хеш успешно проверен ({hash_file_name})',
	'validating_hash_failed': 'Ошибка проверки хеша ({hash_file_name})',
	'validating_source_succeed': 'Источник успешно проверен ({source_file_name})',
	'validating_source_failed': 'Ошибка проверки источника ({source_file_name})',
	'deleting_corrupt_source': 'Удаление поврежденного источника ({source_file_name})',
	'time_ago_now': 'Только что',
	'time_ago_minutes': '{minutes} минут назад',
	'time_ago_hours': '{hours} часов {minutes} минут назад',
	'time_ago_days': '{days} дней {hours} часов {minutes} минут назад',
	'point': '.',
	'comma': ',',
	'colon': ':',
	'question_mark': '?',
	'exclamation_mark': '!',
	'help':
	{
		# installer
		'install_dependency': 'выберите вариант {dependency} для установки',
		'skip_conda': 'пропустить проверку окружения conda',
		# paths
		'config_path': 'выберите конфигурационный файл для переопределения настроек по умолчанию',
		'temp_path': 'укажите директорию для временных ресурсов',
		'jobs_path': 'укажите директорию для хранения задач',
		'source_paths': 'выберите пути к изображению или аудио',
		'target_path': 'выберите путь к изображению или видео',
		'output_path': 'укажите изображение или видео в директории',
		# patterns
		'source_pattern': 'выберите шаблон изображения или аудио',
		'target_pattern': 'выберите шаблон изображения или видео',
		'output_pattern': 'укажите шаблон изображения или видео',
		# face detector
		'face_detector_model': 'Модель детектора лиц',
		'face_detector_size': 'Размер детектора',
		'face_detector_angles': 'укажите углы для поворота кадра перед обнаружением лиц',
		'face_detector_score': 'Порог детектора',
		# face landmarker
		'face_landmarker_model': 'Модель определения ключевых точек',
		'face_landmarker_score': 'Порог определения точек',
		# face selector
		'face_selector_mode': 'Режим выбора лица',
		'face_selector_order': 'Порядок лиц',
		'face_selector_age_start': 'фильтрация обнаруженных лиц по начальному возрасту',
		'face_selector_age_end': 'фильтрация обнаруженных лиц по конечному возрасту',
		'face_selector_gender': 'Пол',
		'face_selector_race': 'Раса',
		'reference_face_position': 'укажите позицию, используемую для создания эталонного лица',
		'reference_face_distance': 'укажите сходство между эталонным и целевым лицом',
		'reference_frame_number': 'укажите кадр, используемый для создания эталонного лица',
		# face masker
		'face_occluder_model': 'выберите модель, отвечающую за маску окклюзии',
		'face_parser_model': 'выберите модель, отвечающую за маску области',
		'face_mask_types': 'комбинирование различных типов масок лица (варианты: {choices})',
		'face_mask_blur': 'укажите степень размытия для маски',
		'face_mask_padding': 'применить верхний, правый, нижний и левый отступы к маске',
		'face_mask_regions': 'выберите черты лица для маски (варианты: {choices})',
		# frame extraction
		'trim_frame_start': 'укажите начальный кадр целевого видео',
		'trim_frame_end': 'укажите конечный кадр целевого видео',
		'temp_frame_format': 'укажите формат временных ресурсов',
		'keep_temp': 'сохранить временные ресурсы после обработки',
		# output creation
		'output_image_quality': 'укажите качество изображения, влияющее на сжатие',
		'output_image_resolution': 'Разрешение выходного изображения',
		'output_audio_encoder': 'укажите кодировщик для аудио',
		'output_audio_quality': 'укажите качество аудио, влияющее на сжатие',
		'output_audio_volume': 'укажите громкость аудио на основе целевого видео',
		'output_video_encoder': 'укажите кодировщик для видео',
		'output_video_preset': 'баланс между быстрой обработкой и размером файла',
		'output_video_quality': 'укажите качество видео, влияющее на сжатие',
		'output_video_resolution': 'Разрешение выходного видео',
		'output_video_fps': 'FPS выходного видео',
		# processors
		'processors': 'Процессоры',
		'age_modifier_model': 'выберите модель, отвечающую за изменение возраста лица',
		'age_modifier_direction': 'укажите направление, в котором следует изменять возраст',
		'deep_swapper_model': 'выберите модель, отвечающую за замену лица',
		'deep_swapper_morph': 'морфинг между лицом источника и целевыми лицами',
		'expression_restorer_model': 'выберите модель, отвечающую за восстановление выражения',
		'expression_restorer_factor': 'фактор восстановления выражения с целевого лица',
		'face_debugger_items': 'загрузить один или несколько процессоров (варианты: {choices})',
		'face_editor_model': 'Модель редактирования лиц',
		'face_editor_eyebrow_direction': 'укажите направление бровей',
		'face_editor_eye_gaze_horizontal': 'укажите горизонтальный взгляд глаз',
		'face_editor_eye_gaze_vertical': 'укажите вертикальный взгляд глаз',
		'face_editor_eye_open_ratio': 'укажите степень открытия глаз',
		'face_editor_lip_open_ratio': 'укажите степень открытия губ',
		'face_editor_mouth_grim': 'укажите гримасу рта',
		'face_editor_mouth_pout': 'укажите надутость губ',
		'face_editor_mouth_purse': 'укажите поджатие губ',
		'face_editor_mouth_smile': 'укажите улыбку',
		'face_editor_mouth_position_horizontal': 'укажите горизонтальное положение рта',
		'face_editor_mouth_position_vertical': 'укажите вертикальное положение рта',
		'face_editor_head_pitch': 'укажите наклон головы',
		'face_editor_head_yaw': 'укажите поворот головы вбок',
		'face_editor_head_roll': 'укажите поворот головы',
		'face_enhancer_model': 'Модель улучшения лиц',
		'face_enhancer_blend': 'смешивание улучшенного лица с предыдущим',
		'face_enhancer_weight': 'укажите степень веса, применяемого к лицу',
		'face_swapper_model': 'Модель замены лиц',
		'face_swapper_pixel_boost': 'выберите разрешение усиления пикселей для замены лица',
		'frame_colorizer_model': 'Модель раскраски кадров',
		'frame_colorizer_size': 'укажите размер кадра для раскраски',
		'frame_colorizer_blend': 'смешивание раскрашенного с предыдущим кадром',
		'frame_enhancer_model': 'Модель улучшения кадров',
		'frame_enhancer_blend': 'смешивание улучшенного с предыдущим кадром',
		'lip_syncer_model': 'Модель синхронизации губ',
		# uis
		'open_browser': 'открыть браузер после запуска программы',
		'ui_layouts': 'запустить один или несколько макетов интерфейса (варианты: {choices}, ...)',
		'ui_workflow': 'выберите рабочий процесс интерфейса',
		# execution
		'execution_device_id': 'укажите устройство для обработки',
		'execution_providers': 'выполнение с использованием разных провайдеров (варианты: {choices}, ...)',
		'execution_thread_count': 'укажите количество параллельных потоков при обработке',
		'execution_queue_count': 'укажите количество кадров, обрабатываемых каждым потоком',
		# download
		'download_providers': 'загрузка с использованием разных провайдеров (варианты: {choices}, ...)',
		'download_scope': 'укажите область загрузки',
		# memory
		'video_memory_strategy': 'баланс между быстрой обработкой и низким использованием VRAM',
		'system_memory_limit': 'ограничение доступной RAM для использования при обработке',
		# misc
		'log_level': 'настройка уровня отображаемых сообщений в терминале',
		'halt_on_error': 'остановить программу при возникновении ошибки',
		# run
		'run': 'запустить программу',
		'headless_run': 'запустить программу в безголовом режиме',
		'batch_run': 'запустить программу в пакетном режиме',
		'force_download': 'принудительная автоматическая загрузка и выход',
		# jobs
		'job_id': 'указать ID задачи',
		'job_status': 'указать статус задачи',
		'step_index': 'указать индекс шага',
		# job manager
		'job_list': 'список задач по статусу',
		'job_create': 'создать черновую задачу',
		'job_submit': 'отправить черновую задачу в очередь',
		'job_submit_all': 'отправить все черновые задачи в очередь',
		'job_delete': 'удалить черновую, очередную, неудачную или завершенную задачу',
		'job_delete_all': 'удалить все черновые, очередные, неудачные и завершенные задачи',
		'job_add_step': 'добавить шаг в черновую задачу',
		'job_remix_step': 'ремикс предыдущего шага из черновой задачи',
		'job_insert_step': 'вставить шаг в черновую задачу',
		'job_remove_step': 'удалить шаг из черновой задачи',
		# job runner
		'job_run': 'запустить задачу из очереди',
		'job_run_all': 'запустить все задачи из очереди',
		'job_retry': 'повторить неудачную задачу',
		'job_retry_all': 'повторить все неудачные задачи'
	},
	'about':
	{
		'become_a_member': 'стать участником',
		'join_our_community': 'присоединиться к сообществу',
		'read_the_documentation': 'прочитать документацию'
	},
	'uis':
	{
		'age_modifier_direction_slider': 'НАПРАВЛЕНИЕ МОДИФИКАТОРА ВОЗРАСТА',
		'age_modifier_model_dropdown': 'МОДЕЛЬ МОДИФИКАТОРА ВОЗРАСТА',
		'apply_button': 'ПРИМЕНИТЬ',
		'benchmark_cycles_slider': 'ЦИКЛЫ ТЕСТИРОВАНИЯ',
		'benchmark_runs_checkbox_group': 'ЗАПУСКИ ТЕСТИРОВАНИЯ',
		'clear_button': 'ОЧИСТИТЬ',
		'common_options_checkbox_group': 'ОПЦИИ',
		'download_providers_checkbox_group': 'ПРОВАЙДЕРЫ ЗАГРУЗКИ',
		'deep_swapper_model_dropdown': 'МОДЕЛЬ DEEP SWAPPER',
		'deep_swapper_morph_slider': 'МОРФИНГ DEEP SWAPPER',
		'execution_providers_checkbox_group': 'ПРОВАЙДЕРЫ ВЫПОЛНЕНИЯ',
		'execution_queue_count_slider': 'КОЛИЧЕСТВО ОЧЕРЕДЕЙ ВЫПОЛНЕНИЯ',
		'execution_thread_count_slider': 'КОЛИЧЕСТВО ПОТОКОВ ВЫПОЛНЕНИЯ',
		'expression_restorer_factor_slider': 'ФАКТОР ВОССТАНОВЛЕНИЯ ВЫРАЖЕНИЯ',
		'expression_restorer_model_dropdown': 'МОДЕЛЬ ВОССТАНОВЛЕНИЯ ВЫРАЖЕНИЯ',
		'face_debugger_items_checkbox_group': 'ЭЛЕМЕНТЫ ОТЛАДКИ ЛИЦА',
		'face_detector_angles_checkbox_group': 'УГЛЫ ДЕТЕКТОРА ЛИЦ',
		'face_detector_model_dropdown': 'МОДЕЛЬ ДЕТЕКТОРА ЛИЦ',
		'face_detector_score_slider': 'ПОРОГ ДЕТЕКТОРА ЛИЦ',
		'face_detector_size_dropdown': 'РАЗМЕР ДЕТЕКТОРА ЛИЦ',
		'face_editor_eyebrow_direction_slider': 'НАПРАВЛЕНИЕ БРОВЕЙ',
		'face_editor_eye_gaze_horizontal_slider': 'ВЗГЛЯД ПО ГОРИЗОНТАЛИ',
		'face_editor_eye_gaze_vertical_slider': 'ВЗГЛЯД ПО ВЕРТИКАЛИ',
		'face_editor_eye_open_ratio_slider': 'СТЕПЕНЬ ОТКРЫТИЯ ГЛАЗ',
		'face_editor_head_pitch_slider': 'НАКЛОН ГОЛОВЫ',
		'face_editor_head_roll_slider': 'ПОВОРОТ ГОЛОВЫ',
		'face_editor_head_yaw_slider': 'ПОВОРОТ ГОЛОВЫ ВБОК',
		'face_editor_lip_open_ratio_slider': 'СТЕПЕНЬ ОТКРЫТИЯ ГУБ',
		'face_editor_model_dropdown': 'МОДЕЛЬ РЕДАКТОРА ЛИЦ',
		'face_editor_mouth_grim_slider': 'ГРИМАСА РТА',
		'face_editor_mouth_position_horizontal_slider': 'ПОЛОЖЕНИЕ РТА ПО ГОРИЗОНТАЛИ',
		'face_editor_mouth_position_vertical_slider': 'ПОЛОЖЕНИЕ РТА ПО ВЕРТИКАЛИ',
		'face_editor_mouth_pout_slider': 'НАДУТОСТЬ ГУБ',
		'face_editor_mouth_purse_slider': 'ПОДЖАТИЕ ГУБ',
		'face_editor_mouth_smile_slider': 'УЛЫБКА',
		'face_enhancer_blend_slider': 'СМЕШИВАНИЕ УЛУЧШЕНИЯ ЛИЦА',
		'face_enhancer_model_dropdown': 'МОДЕЛЬ УЛУЧШЕНИЯ ЛИЦА',
		'face_enhancer_weight_slider': 'ВЕС УЛУЧШЕНИЯ ЛИЦА',
		'face_landmarker_model_dropdown': 'МОДЕЛЬ ОПРЕДЕЛЕНИЯ КЛЮЧЕВЫХ ТОЧЕК',
		'face_landmarker_score_slider': 'ПОРОГ ОПРЕДЕЛЕНИЯ ТОЧЕК',
		'face_mask_blur_slider': 'РАЗМЫТИЕ МАСКИ ЛИЦА',
		'face_mask_padding_bottom_slider': 'ОТСТУП МАСКИ СНИЗУ',
		'face_mask_padding_left_slider': 'ОТСТУП МАСКИ СЛЕВА',
		'face_mask_padding_right_slider': 'ОТСТУП МАСКИ СПРАВА',
		'face_mask_padding_top_slider': 'ОТСТУП МАСКИ СВЕРХУ',
		'face_mask_regions_checkbox_group': 'ОБЛАСТИ МАСКИ ЛИЦА',
		'face_mask_types_checkbox_group': 'ТИПЫ МАСКИ ЛИЦА',
		'face_selector_age_range_slider': 'ВОЗРАСТ',
		'face_selector_gender_dropdown': 'ПОЛ',
		'face_selector_mode_dropdown': 'РЕЖИМ ВЫБОРА ЛИЦА',
		'face_selector_order_dropdown': 'ПОРЯДОК ЛИЦ',
		'face_selector_race_dropdown': 'РАСА',
		'face_swapper_model_dropdown': 'МОДЕЛЬ ЗАМЕНЫ ЛИЦ',
		'face_swapper_pixel_boost_dropdown': 'УЛУЧШЕНИЕ ПИКСЕЛЕЙ',
		'face_occluder_model_dropdown': 'МОДЕЛЬ МАСКИРОВАНИЯ ЛИЦА',
		'face_parser_model_dropdown': 'МОДЕЛЬ ПАРСЕРА ЛИЦА',
		'frame_colorizer_blend_slider': 'СМЕШИВАНИЕ РАСКРАСКИ КАДРОВ',
		'frame_colorizer_model_dropdown': 'МОДЕЛЬ РАСКРАСКИ КАДРОВ',
		'frame_colorizer_size_dropdown': 'РАЗМЕР РАСКРАСКИ КАДРОВ',
		'frame_enhancer_blend_slider': 'СМЕШИВАНИЕ УЛУЧШЕНИЯ КАДРОВ',
		'frame_enhancer_model_dropdown': 'МОДЕЛЬ УЛУЧШЕНИЯ КАДРОВ',
		'job_list_status_checkbox_group': 'СТАТУС ЗАДАЧИ',
		'job_manager_job_action_dropdown': 'ДЕЙСТВИЕ ЗАДАЧИ',
		'job_manager_job_id_dropdown': 'ID ЗАДАЧИ',
		'job_manager_step_index_dropdown': 'ИНДЕКС ШАГА',
		'job_runner_job_action_dropdown': 'ДЕЙСТВИЕ ЗАДАЧИ',
		'job_runner_job_id_dropdown': 'ID ЗАДАЧИ',
		'lip_syncer_model_dropdown': 'МОДЕЛЬ СИНХРОНИЗАЦИИ ГУБ',
		'log_level_dropdown': 'УРОВЕНЬ ЛОГИРОВАНИЯ',
		'output_audio_encoder_dropdown': 'КОДИРОВЩИК АУДИО',
		'output_audio_quality_slider': 'КАЧЕСТВО АУДИО',
		'output_audio_volume_slider': 'ГРОМКОСТЬ АУДИО',
		'output_image_or_video': 'ВЫХОДНОЕ ИЗОБРАЖЕНИЕ ИЛИ ВИДЕО',
		'output_image_quality_slider': 'КАЧЕСТВО ИЗОБРАЖЕНИЯ',
		'output_image_resolution_dropdown': 'РАЗРЕШЕНИЕ ИЗОБРАЖЕНИЯ',
		'output_path_textbox': 'ПУТЬ ВЫВОДА',
		'output_video_encoder_dropdown': 'КОДИРОВЩИК ВИДЕО',
		'output_video_fps_slider': 'FPS ВИДЕО',
		'output_video_preset_dropdown': 'ПРЕСЕТ ВИДЕО',
		'output_video_quality_slider': 'КАЧЕСТВО ВИДЕО',
		'output_video_resolution_dropdown': 'РАЗРЕШЕНИЕ ВИДЕО',
		'preview_frame_slider': 'КАДР ПРЕДПРОСМОТРА',
		'preview_image': 'ПРЕДПРОСМОТР',
		'processors_checkbox_group': 'ПРОЦЕССОРЫ',
		'reference_face_distance_slider': 'ДИСТАНЦИЯ ЭТАЛОННОГО ЛИЦА',
		'reference_face_gallery': 'ГАЛЕРЕЯ ЭТАЛОННЫХ ЛИЦ',
		'refresh_button': 'ОБНОВИТЬ',
		'source_file': 'ИСТОЧНИК',
		'start_button': 'СТАРТ',
		'stop_button': 'СТОП',
		'output_image_or_video': 'ВЫХОДНОЕ ИЗОБРАЖЕНИЕ ИЛИ ВИДЕО',
		'output_path_textbox': 'ПУТЬ ВЫВОДА',
		'preview_image': 'ПРЕДПРОСМОТР',
		'processors_checkbox_group': 'ПРОЦЕССОРЫ',
		'reference_face_distance_slider': 'ДИСТАНЦИЯ ЭТАЛОННОГО ЛИЦА',
		'reference_face_gallery': 'ГАЛЕРЕЯ ЭТАЛОННЫХ ЛИЦ',
		'refresh_button': 'ОБНОВИТЬ',
		'source_file': 'ИСТОЧНИК',
		'start_button': 'СТАРТ',
		'stop_button': 'СТОП',
		'system_memory_limit_slider': 'ОГРАНИЧЕНИЕ ОПЕРАТИВНОЙ ПАМЯТИ',
		'target_file': 'ЦЕЛЬ',
		'temp_frame_format_dropdown': 'ФОРМАТ ВРЕМЕННЫХ КАДРОВ',
		'terminal_textbox': 'ТЕРМИНАЛ',
		'trim_frame_slider': 'ОБРЕЗКА КАДРОВ',
		'ui_workflow': 'РАБОЧИЙ ПРОЦЕСС UI',
		'video_memory_strategy_dropdown': 'СТРАТЕГИЯ ВИДЕОПАМЯТИ',
		'webcam_fps_slider': 'FPS ВЕБ-КАМЕРЫ',
		'webcam_image': 'ВЕБ-КАМЕРА',
		'webcam_device_id_dropdown': 'ID ВЕБ-КАМЕРЫ',
		'webcam_mode_radio': 'РЕЖИМ ВЕБ-КАМЕРЫ',
		'webcam_resolution_dropdown': 'РАЗРЕШЕНИЕ ВЕБ-КАМЕРЫ',
		'system_memory_limit_slider': 'SYSTEM MEMORY LIMIT',
		'target_file': 'TARGET',
		'temp_frame_format_dropdown': 'TEMP FRAME FORMAT',
		'terminal_textbox': 'TERMINAL',
		'trim_frame_slider': 'TRIM FRAME',
		'ui_workflow': 'UI WORKFLOW',
		'video_memory_strategy_dropdown': 'VIDEO MEMORY STRATEGY',
		'webcam_fps_slider': 'WEBCAM FPS',
		'webcam_image': 'Веб-камера',
		'webcam_device_id_dropdown': 'WEBCAM DEVICE ID',
		'webcam_resolution_dropdown': 'WEBCAM RESOLUTION',
		'source_image': 'Исходное изображение',
		'target_image': 'Целевое изображение',
		'target_video': 'Целевое видео',
		'output_path': 'Путь для сохранения',
		'face_selector_age': 'Возраст',
		'face_selector_gender': 'Пол',
		'face_selector_race': 'Раса',
		'face_selector_mode': 'Режим выбора лица',
		'face_selector_order': 'Порядок лиц',
		'face_detector_model': 'Модель детектора лиц',
		'face_detector_size': 'Размер детектора',
		'face_detector_score': 'Порог детектора',
		'face_landmarker_model': 'Модель определения ключевых точек',
		'face_landmarker_score': 'Порог определения точек',
		'face_swapper_model': 'Модель замены лиц',
		'face_enhancer_model': 'Модель улучшения лиц',
		'face_editor_model': 'Модель редактирования лиц',
		'frame_enhancer_model': 'Модель улучшения кадров',
		'frame_colorizer_model': 'Модель раскраски кадров',
		'lip_syncer_model': 'Модель синхронизации губ',
		'output_video_fps': 'FPS выходного видео',
		'output_video_resolution': 'Разрешение выходного видео',
		'output_image_resolution': 'Разрешение выходного изображения',
		'processors': 'Процессоры',
		'streaming': 'Трансляция',
		'analysing': 'Анализ',
		'downloading': 'Загрузка',
		'validating': 'Проверка',
		'validating_hash_succeed': 'Хеш успешно проверен ({hash_file_name})',
		'validating_hash_failed': 'Ошибка проверки хеша ({hash_file_name})',
		'validating_source_succeed': 'Источник успешно проверен ({source_file_name})',
		'validating_source_failed': 'Ошибка проверки источника ({source_file_name})',
		'deleting_corrupt_source': 'Удаление поврежденного источника ({source_file_name})',
		'time_ago_days': '{days} дней {hours} часов {minutes} минут назад',
		'time_ago_hours': '{hours} часов {minutes} минут назад',
		'time_ago_minutes': '{minutes} минут назад',
		'time_ago_now': 'Только что',
		'job_created': 'Задача {job_id} создана',
		'job_not_created': 'Ошибка создания задачи {job_id}',
		'job_submitted': 'Задача {job_id} отправлена',
		'job_not_submitted': 'Ошибка отправки задачи {job_id}',
		'job_all_submitted': 'Все задачи отправлены',
		'job_all_not_submitted': 'Ошибка отправки всех задач',
		'job_deleted': 'Задача {job_id} удалена',
		'job_not_deleted': 'Ошибка удаления задачи {job_id}',
		'job_all_deleted': 'Все задачи удалены',
		'job_all_not_deleted': 'Ошибка удаления всех задач',
		'job_step_added': 'Шаг добавлен в задачу {job_id}',
		'job_step_not_added': 'Ошибка добавления шага в задачу {job_id}',
		'job_remix_step_added': 'Шаг ремикса добавлен в задачу {job_id} (шаг {step_index})',
		'job_remix_step_not_added': 'Ошибка добавления шага ремикса в задачу {job_id} (шаг {step_index})',
		'job_step_inserted': 'Шаг вставлен в задачу {job_id} (шаг {step_index})',
		'job_step_not_inserted': 'Ошибка вставки шага в задачу {job_id} (шаг {step_index})',
		'job_step_removed': 'Шаг удален из задачи {job_id} (шаг {step_index})',
		'job_step_not_removed': 'Ошибка удаления шага из задачи {job_id} (шаг {step_index})',
		'job_step': 'Шаг {step_current} из {step_total}',
		'running_job': 'Запуск задачи {job_id}',
		'processing_job_succeed': 'Задача {job_id} успешно обработана',
		'processing_job_failed': 'Ошибка обработки задачи {job_id}',
		'running_jobs': 'Запуск задач',
		'processing_jobs_succeed': 'Все задачи успешно обработаны',
		'processing_jobs_failed': 'Ошибка обработки задач',
		'retrying_job': 'Повторная попытка задачи {job_id}',
		'retrying_jobs': 'Повторная попытка задач'
	}
}


def get(key : str) -> Optional[str]:
	if '.' in key:
		section, name = key.split('.')
		if section in WORDING and name in WORDING.get(section):
			return WORDING.get(section).get(name)
	if key in WORDING:
		return WORDING.get(key)
	return None
